CREATE TABLE "LOCALIZATION_SETTINGS" 
 (	"ID" RAW(16) DEFAULT SYS_GUID(), 
"ENTITY_ID" RAW(16), 
"PARENT_ID" RAW(16), 
"LANGUAGE" VARCHAR2(255 BYTE), 
"FORMATTING" VARCHAR2(255 BYTE)
 );

CREATE UNIQUE INDEX "VITALI_SHCHARBIN"."LOCALIZATION_SETTINGS_PK" ON "VITALI_SHCHARBIN"."LOCALIZATION_SETTINGS" ("ID");

ALTER TABLE "LOCALIZATION_SETTINGS" ADD CONSTRAINT "LOCALIZATION_SETTINGS_PK" PRIMARY KEY ("ID");

ALTER TABLE "LOCALIZATION_SETTINGS" MODIFY ("FORMATTING" NOT NULL ENABLE);
ALTER TABLE "LOCALIZATION_SETTINGS" MODIFY ("LANGUAGE" NOT NULL ENABLE);
ALTER TABLE "LOCALIZATION_SETTINGS" MODIFY ("ENTITY_ID" NOT NULL ENABLE);
ALTER TABLE "LOCALIZATION_SETTINGS" MODIFY ("ID" CONSTRAINT "NNC_LOCALIZATION_SETTINGS_ID" NOT NULL ENABLE);
